[2024-08-13T16:10:41.709+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-13T16:10:42.161+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.no_new_data backfill__2024-02-28T00:00:00+00:00 [queued]>
[2024-08-13T16:10:42.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.no_new_data backfill__2024-02-28T00:00:00+00:00 [queued]>
[2024-08-13T16:10:42.205+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-13T16:10:42.242+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): no_new_data> on 2024-02-28 00:00:00+00:00
[2024-08-13T16:10:42.265+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1234) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-13T16:10:42.271+0000] {standard_task_runner.py:63} INFO - Started process 1245 to run task
[2024-08-13T16:10:42.270+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'no_new_data', 'backfill__2024-02-28T00:00:00+00:00', '--job-id', '251', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpxu9m9zno']
[2024-08-13T16:10:42.278+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask no_new_data
[2024-08-13T16:10:42.327+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-13T16:10:42.429+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.no_new_data backfill__2024-02-28T00:00:00+00:00 [running]> on host ubuntu
[2024-08-13T16:10:42.687+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='no_new_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-02-28T00:00:00+00:00'
[2024-08-13T16:10:42.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-13T16:10:42.722+0000] {logging_mixin.py:188} INFO - Data are inserted, skipping this run
[2024-08-13T16:10:42.724+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-13T16:10:42.726+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-13T16:10:42.752+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=no_new_data, run_id=backfill__2024-02-28T00:00:00+00:00, execution_date=20240228T000000, start_date=20240813T161042, end_date=20240813T161042
[2024-08-13T16:10:42.815+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-13T16:10:42.852+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-13T16:10:42.875+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
