[2024-08-14T05:42:06.820+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T05:42:06.834+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-05-02T00:00:00+00:00 [queued]>
[2024-08-14T05:42:06.841+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-05-02T00:00:00+00:00 [queued]>
[2024-08-14T05:42:06.842+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T05:42:06.983+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_inserted> on 2024-05-02 00:00:00+00:00
[2024-08-14T05:42:06.990+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3839) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T05:42:06.992+0000] {standard_task_runner.py:63} INFO - Started process 3841 to run task
[2024-08-14T05:42:06.992+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'check_inserted', 'backfill__2024-05-02T00:00:00+00:00', '--job-id', '771', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpwq2r4wqz']
[2024-08-14T05:42:06.995+0000] {standard_task_runner.py:91} INFO - Job 771: Subtask check_inserted
[2024-08-14T05:42:07.057+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-05-02T00:00:00+00:00 [running]> on host ubuntu
[2024-08-14T05:42:07.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='check_inserted' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-05-02T00:00:00+00:00'
[2024-08-14T05:42:07.244+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T05:42:07.268+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-08-14T05:42:07.270+0000] {logging_mixin.py:188} INFO - 2024-05-02
[2024-08-14T05:42:07.271+0000] {logging_mixin.py:188} INFO - <class 'pendulum.date.Date'>
[2024-08-14T05:42:07.293+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_raw' for task execution.
[2024-08-14T05:42:07.297+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-08-14T05:42:07.299+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-14T05:42:08.250+0000] {logging_mixin.py:188} INFO - Connected Successfully!
[2024-08-14T05:42:08.252+0000] {logging_mixin.py:188} INFO - 
        SELECT MAX(INPUT_DATE) FROM RAW_WEATHER_DATA;
    
[2024-08-14T05:42:08.381+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-14T05:42:08.383+0000] {logging_mixin.py:188} INFO - 2024-02-08
[2024-08-14T05:42:08.384+0000] {logging_mixin.py:188} INFO - <class 'pendulum.date.Date'>
[2024-08-14T05:42:08.385+0000] {connection.py:762} INFO - closed
[2024-08-14T05:42:08.481+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-08-14T05:42:08.591+0000] {logging_mixin.py:188} INFO - invoke_lambda_task task will execute
[2024-08-14T05:42:08.594+0000] {python.py:237} INFO - Done. Returned value was: invoke_lambda_task
[2024-08-14T05:42:08.596+0000] {branch.py:36} INFO - Branch into invoke_lambda_task
[2024-08-14T05:42:08.597+0000] {skipmixin.py:178} INFO - Following branch invoke_lambda_task
[2024-08-14T05:42:08.636+0000] {skipmixin.py:246} INFO - Skipping tasks [('no_new_data', -1)]
[2024-08-14T05:42:08.687+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T05:42:08.718+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=check_inserted, run_id=backfill__2024-05-02T00:00:00+00:00, execution_date=20240502T000000, start_date=20240814T054206, end_date=20240814T054208
[2024-08-14T05:42:08.776+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-14T05:42:08.817+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T05:42:08.821+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
