[2024-08-14T07:27:50.397+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T07:27:50.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-14T07:27:50.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-14T07:27:50.657+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T07:27:50.677+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-08-11 00:00:00+00:00
[2024-08-14T07:27:50.687+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T07:27:50.689+0000] {standard_task_runner.py:63} INFO - Started process 6104 to run task
[2024-08-14T07:27:50.690+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-08-11T00:00:00+00:00', '--job-id', '1075', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpvgdajlc4']
[2024-08-14T07:27:50.693+0000] {standard_task_runner.py:91} INFO - Job 1075: Subtask invoke_lambda_task
[2024-08-14T07:27:50.754+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-11T00:00:00+00:00 [running]> on host ubuntu
[2024-08-14T07:27:50.869+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-08-11T00:00:00+00:00'
[2024-08-14T07:27:50.871+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T07:27:50.910+0000] {logging_mixin.py:188} INFO - Data_Weather-20240811.csv
[2024-08-14T07:27:50.911+0000] {logging_mixin.py:188} INFO - 2024/08/11
[2024-08-14T07:27:50.911+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/08/11", "file_name": "Data_Weather-20240811.csv"}
[2024-08-14T07:27:50.911+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/08/11&file_name=Data_Weather-20240811.csv
[2024-08-14T07:28:20.564+0000] {logging_mixin.py:188} INFO - Failed to invoke Lambda function.
[2024-08-14T07:28:20.565+0000] {logging_mixin.py:188} INFO - Response: {"message": "Endpoint request timed out"}
[2024-08-14T07:28:20.568+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T07:28:20.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T07:28:20.581+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-08-11T00:00:00+00:00, execution_date=20240811T000000, start_date=20240814T072750, end_date=20240814T072820
[2024-08-14T07:28:20.638+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-14T07:28:20.655+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-14T07:28:20.659+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-16T10:03:14.938+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T10:03:15.204+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-16T10:03:15.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-16T10:03:15.233+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-16T10:03:15.271+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-08-11 00:00:00+00:00
[2024-08-16T10:03:15.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2054) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T10:03:15.287+0000] {standard_task_runner.py:63} INFO - Started process 2056 to run task
[2024-08-16T10:03:15.288+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-08-11T00:00:00+00:00', '--job-id', '1235', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmphwdw5vn6']
[2024-08-16T10:03:15.293+0000] {standard_task_runner.py:91} INFO - Job 1235: Subtask invoke_lambda_task
[2024-08-16T10:03:15.407+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-11T00:00:00+00:00 [running]> on host ubuntu
[2024-08-16T10:03:15.583+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-08-11T00:00:00+00:00'
[2024-08-16T10:03:15.586+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T10:03:15.633+0000] {logging_mixin.py:188} INFO - Data_Weather-20240811.csv
[2024-08-16T10:03:15.635+0000] {logging_mixin.py:188} INFO - 2024/08/11
[2024-08-16T10:03:15.636+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/08/11", "file_name": "Data_Weather-20240811.csv"}
[2024-08-16T10:03:15.637+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/08/11&file_name=Data_Weather-20240811.csv
[2024-08-16T10:03:45.279+0000] {logging_mixin.py:188} INFO - Failed to invoke Lambda function.
[2024-08-16T10:03:45.281+0000] {logging_mixin.py:188} INFO - Response: {"message": "Endpoint request timed out"}
[2024-08-16T10:03:45.285+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-16T10:03:45.288+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T10:03:45.304+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-08-11T00:00:00+00:00, execution_date=20240811T000000, start_date=20240816T100315, end_date=20240816T100345
[2024-08-16T10:03:45.346+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-16T10:03:45.385+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-16T10:03:45.388+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
